# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('svg', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idm_card.Identity'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('identity', 'sequence_number')]),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together=set([('identity', 'sequence_number')]),
        ),
    ]
