# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idm_card', '0002_auto_20170729_2210'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE SEQUENCE card_number MINVALUE 1000000',
            'DROP SEQUENCE card_number',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE idm_card_card ADD card_number INTEGER DEFAULT nextval('card_number')",
                    "ALTER TABLE idm_card_card DROP card_number",
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='card',
                    name='card_number',
                    field=models.IntegerField(),
                    preserve_default=False,
                ),
            ],
        ),
    ]
