# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idm_card', '0003_card_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='status',
            new_name='state',
        ),
    ]
